# Generated by Django 5.1.1 on 2024-09-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_todoitem_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoItem',
            new_name='Item',
        ),
    ]
